### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by matejdro** [moverest/wl-kbptr#10]
Hello.

Thanks for this utility, it's super useful as a replacement for warpd on Wayland.

I realise that button simulation is more handled by sway, but I was wondering if there is a way to simulate mouse wheel scrolling under cursor? 

There does not appear to be a `seat` command for scrolling.

**Comment by moverest** [comment]
I'm not really sure either how it works with the Sway commands from reading the documentation.

> From sway-input(5):
> 
> **seat** <seat> cursor press|release button[1-9]|\<event-name-or-code\>
>
> Simulate pressing (or releasing) the specified mouse button on the  specified  seat.  The  button  can either be provided as a button event name or event code, which can be obtained from `libinput debug-events`, or as an x11 mouse button (`button[1-9]`). If using `button[4-7]`, which map  to  axes,  an axis  event  will  be simulated, however press and release will be ignored and both will occur.
>
> Deprecated: use the virtual-pointer Wayland protocol instead.

Having said that, it says that this is deprecated so I'm thinking of adding a CLI for the sole purpose of simulating these events. It should be pretty straightforward to implement from reading [`wayvnc`'s code](https://github.com/any1/wayvnc/blob/50f095d6e873302277292e0b46040e861b05d9fb/src/pointer.c).

**Comment by matejdro** [comment]
This appears to be possible using [wlctrl](https://git.sr.ht/~brocellous/wlrctl) activity:

`wlrctl pointer scroll 10 0`
