### ISSUE TITLE
Pointer is off-center - offset setting in config?

### ISSUE THREAD

**Issue by Ascyt** [moverest/wl-kbptr#18]
Hey, so on my system (Arch with Hyprland) when I use the tool, the actual position of the mouse cursor appears to always be a little bit higher up than what the cursor of this tool shows. 

An easy fix for that would be some sort of way to define an off-set x and y value, so it's possible to correct errors like this with manual testing.

**Comment by Ascyt** [comment]
Okay I don't really know what I did wrong with installing lol but when cloned the project and built it myself and ran that it worked fine without offset... Weird

**Comment by moverest** [comment]
That reminds me that I haven't made a release in a while. There has been quite a lot of changes since the last one.

**Comment by moverest** [comment]
I suspect your issue was solved with #7.

**Comment by Ascyt** [comment]
Yes, that is correct, thank you
