### ISSUE TITLE
Tile Mode Configuring Sizes

### ISSUE THREAD

**Issue by RockasMockas** [moverest/wl-kbptr#21]
First of all wanted to say thanks for creating such a great tool.

I wanted to ask if there are plans/specifically if there is anything in the implementation that prevents adding tile size/font size configuration settings for `[mode_tile]`? I've ended up with a flow where I just need to get to the rough location on the screen and have modulated cursor movement for the last 5%, and so I don't end up using the bisection. It would be great to be able to configure the size of each of the tiles, and also the font sizes so it can work on various screen sizes.

**Comment by moverest** [comment]
The size of the tiles is set by the max between the [`MIN_SUB_AREA_SIZE`](https://github.com/moverest/wl-kbptr/blob/main/src/mode_tile.c#L12) constant and the screen area divided by the maximum number of tiles possible (8<sup>3</sup>). When I added the configuration I wasn't set on whether I wanted to keep that behaviour so I didn't expose the constant then. I don't see a reason why not to do that now.

For the font size, it's half of the tile's height at the moment. It would probably make sense to enable the user to set a curve or maybe something simpler, e.g. min and max sizes.

Another thing I've considered is to enable the user to have a finer-grained control over the characters that are allowed in the label and not limit to the 8 characters in the home row (through this would remain the default). This would allow to have smaller tiles on big screens.

**Comment by RockasMockas** [comment]
Glad to hear you're interested having these included. Made a quick PR with the most valuable updates for me in this direction:
https://github.com/moverest/wl-kbptr/pull/22

Main one I didn't get to for now due to time is having the fine grained character controls. I think its a great idea, especially for allowing people to choose character that would work on just a single hand for split-keyboard setups, so you can get a sort of "mouse-equivalent" feel of having a single hand perform the full mouse flow and taking your other hand off to do something else.
