### ISSUE TITLE
Misaligned overlay when using waybar

### ISSUE THREAD

**Issue by asmigala** [moverest/wl-kbptr#7]
When waybar is visible on the screen, the selection grid is misaligned, having and extra space at the top (seemingly as tall as the bar itself), see screenshots. After hitting enter, the cursor is moved to a position where it should have been if the grid was displayed correctly, i.e. several pixels above the red crosshair.

with waybar:
![yes-waybar](https://github.com/moverest/wl-kbptr/assets/9480152/8c79d724-58d3-4cd5-a1b5-757001c39209)

without waybar:
![no-waybar](https://github.com/moverest/wl-kbptr/assets/9480152/b97d8f59-73b5-42a5-96d6-9c984fa09238)

**Comment by moverest** [comment]
I've just pushed b5a591d0a416fb5280e89696423e42d7beb2f07c to `main` to fix this. Please tell me if it works with your setup.

**Comment by asmigala** [comment]
Yep, work great, thank you very much!
