### ISSUE TITLE
Is it possible to make this compatible with the 'hide when typing' setting in sway?

### ISSUE THREAD

**Issue by rivke41levp656** [moverest/wl-kbptr#8]
When `seat * hide_cursor when-typing enable` is enabled in sway config, any keypress in 'Mouse' mode hides the cursor. 
Is there a way to have the cursor stay visible until the user returns to 'default' mode?

**Comment by moverest** [comment]
This in your Sway configuration should do what you want:

```
bindsym Shift+a seat * hide_cursor when-typing disable, exec 'wl-kbptr, seat * hide_cursor when-typing enable
```

Note however that `wl-kbptr` will not move the cursor until the very end so having the cursor doesn't really do much. Instead it draws a red cross representing where the cursor will land when the user presses `g`, `h`, `b`, `Space` or `Enter`:

![image](https://github.com/moverest/wl-kbptr/assets/19509728/d52231e7-6fbb-4ef5-8c27-fef628818c2d)

![image](https://github.com/moverest/wl-kbptr/assets/19509728/824fac26-635c-408d-a157-bbdac6601fbb)

**Comment by rivke41levp656** [comment]
The reason I wanted the cursor visible is for actions such as:

right-click --> hjkl movement --> left click


I guess changing the binds to this works:
`bindsym Escape seat * hide_cursor when-typing enable, mode default`
`bindsym $super+g seat * hide_cursor when-typing disable, mode Mouse`

**Comment by moverest** [comment]
Oh I see now, it makes sense here.
